### PR TITLE
MINOR: changing injected sort column to be an string instead of an array

### PR DESCRIPTION
**Pull request by spekulatius**
Solves #9 (for me). To be confirmed, if this does the same for you @Taitava

### CODE REVIEW

**Comment by Taitava** [comment]
Hi Peter,

thanks for the PR, the fix seems OK but it seems your editor has changed the indentations of some empty lines. Can you edit this PR so that it doesn't change the empty lines, please?

**Comment by spekulatius** [comment]
Hey @Taitava 

I've adjusted the empty lines. It was trailing spaces which have been removed automatically. Have a look please.

Cheers,
Peter

**Comment by Taitava** [comment]
@spekulatius Thank you very much! :)

**Comment by spekulatius** [comment]
No problem :) Thanks for taking the time to check it and merge it :)

**Pull request merged**
